services:
  db:
    container_name: store-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: store
    ports:
      - "5432:5432"
    volumes:
      - ./data/:/var/lib/postgresql/data